# Generated by Django 2.2.19 on 2021-02-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('volume', models.IntegerField()),
                ('drink_type', models.CharField(choices=[('B', 'Beer'), ('S', 'Shot'), ('W', 'Wine')], max_length=1)),
            ],
        ),
    ]
